### ISSUE TITLE
$file_id type in example file seems incorrect

### ISSUE THREAD

**Issue by colognella** [Eleirbag89/MastodonBotPHP#2]
Maybe it's just for me, but it seems that the example code in [media_bot.php](https://github.com/Eleirbag89/MastodonBotPHP/blob/master/examples/media_bot.php) expects an object for `$response`, however the API returns an array: 

example code: 
    `$file_id = $response->id; // not working for me`

working code: 
    `$file_id = $response['id'];`

I tried both API v1 and v2, same result. After finding out, it works like a charm, thanks for your work!

Thanks for checking.

**Comment by Eleirbag89** [comment]
You are right, fixed ;)
